FROM node:16-alpine3.14

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package.json .
COPY package-lock.json .

RUN npm install

USER node

COPY --chown=node:node . .

EXPOSE 8000

CMD [ "npm", "run", "prod" ]
